// <auto-generated />
using GSBMaas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GSBMaas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231203173503_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GSBMaas.Context.Sabit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AgustosVergi")
                        .HasColumnType("real");

                    b.Property<float>("AralikVergi")
                        .HasColumnType("real");

                    b.Property<float>("BirGunYemek")
                        .HasColumnType("real");

                    b.Property<float>("BirGunYogurt")
                        .HasColumnType("real");

                    b.Property<float>("BirYilHizmetZammi")
                        .HasColumnType("real");

                    b.Property<float>("BuyukSehirYol")
                        .HasColumnType("real");

                    b.Property<float>("EkimVergi")
                        .HasColumnType("real");

                    b.Property<float>("EngelliDerece1")
                        .HasColumnType("real");

                    b.Property<float>("EngelliDerece2")
                        .HasColumnType("real");

                    b.Property<float>("EngelliDerece3")
                        .HasColumnType("real");

                    b.Property<float>("EylulVergi")
                        .HasColumnType("real");

                    b.Property<float>("HaziranVergi")
                        .HasColumnType("real");

                    b.Property<float>("KasimVergi")
                        .HasColumnType("real");

                    b.Property<float>("KresYardimi")
                        .HasColumnType("real");

                    b.Property<float>("KucukSehirYol")
                        .HasColumnType("real");

                    b.Property<float>("MartVergi")
                        .HasColumnType("real");

                    b.Property<float>("MayisVergi")
                        .HasColumnType("real");

                    b.Property<float>("NisanVergi")
                        .HasColumnType("real");

                    b.Property<float>("OcakVergi")
                        .HasColumnType("real");

                    b.Property<float>("SosyalYardim")
                        .HasColumnType("real");

                    b.Property<float>("SubatVergi")
                        .HasColumnType("real");

                    b.Property<float>("TemmuzVergi")
                        .HasColumnType("real");

                    b.Property<float>("VergiDilimKatsayi1")
                        .HasColumnType("real");

                    b.Property<float>("VergiDilimKatsayi2")
                        .HasColumnType("real");

                    b.Property<float>("VergiDilimKatsayi3")
                        .HasColumnType("real");

                    b.Property<int>("VergiDilimOran1")
                        .HasColumnType("int");

                    b.Property<int>("VergiDilimOran2")
                        .HasColumnType("int");

                    b.Property<int>("VergiDilimOran3")
                        .HasColumnType("int");

                    b.Property<float>("VergiIstisnaTutar")
                        .HasColumnType("real");

                    b.Property<float>("Yevmiye1")
                        .HasColumnType("real");

                    b.Property<float>("Yevmiye2")
                        .HasColumnType("real");

                    b.Property<float>("Yevmiye3")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Sabits");
                });
#pragma warning restore 612, 618
        }
    }
}
